### ISSUE TITLE
Ip proxy.

### ISSUE THREAD

**Issue by gaojiuli** [vesche/scanless#1]
I want to use ip proxy to hide myself. But i do not want to change my global ip address. Can i just pass a parameter to set  ip proxy?

**Comment by vesche** [comment]
I'd recommend using proxychains. Add your proxies to `/etc/proxychains.conf` and then just run it using proxychains like `proxychains python scanless.py -t scanme.nmap.org`.

**Comment by shaunpud** [comment]
Requests supports a proxy environment variable, check [here](http://docs.python-requests.org/en/master/user/advanced/#proxies).

Example;
HTTP_PROXY=my.proxy.com:443 python scanless.py -t scanme.nmap.org -s t1shopper
