### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by wan9wu** [vesche/scanless#11]
system:windows10

scanless -a -t 192.168.1.120
Running scanless...
Error, yougetsignal was unable to run.
Error, viewdns was unable to run.

------- hackertarget -------
Starting Nmap 7.01 ( https://nmap.org ) at 2017-08-17 20:14 UTC
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.35 seconds
----------------------------
Error, ipfingerprints was unable to run.

------- pingeu -------
PORT     STATE  SERVICE
21/tcp   closed ftp
22/tcp   closed ssh
23/tcp   closed telnet
25/tcp   closed smtp
53/tcp   closed dns
80/tcp   closed http
139/tcp  closed netbios
443/tcp  closed https
445/tcp  closed smb
3389/tcp closed rdp
----------------------

------- spiderip -------
PORT     STATE  SERVICE
21/tcp   closed ftp
22/tcp   closed ssh
25/tcp   closed smtp
80/tcp   closed http
110/tcp  closed pop3
143/tcp  closed imap
443/tcp  closed https
465/tcp  closed smtps
993/tcp  closed imaps
995/tcp  closed pop3s
1433/tcp closed mssql
3306/tcp closed mysql
3389/tcp closed rdp
5900/tcp closed vnc
8080/tcp closed http-alt
8443/tcp closed https-alt
------------------------
Error, portcheckers was unable to run.
Error, t1shopper was unable to run.

**Comment by vesche** [comment]
Well, you're trying to scan an [internal IP address](https://en.wikipedia.org/wiki/Private_network). The way scanless works is that it uses public port scanning services to scan external IP addresses.
